services:
  auth:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: securemyvoice-app
    restart: always
    ports:
      - "4001:4001"
    volumes:
      - ./:/usr/
    depends_on:
      - mongo
    command: [ "npm","run","start" ]
    develop:
      watch:
        - action: rebuild
          path: .
          target: /usr/

  mongo:
    image: mongo:latest
    container_name: securemyvoice-auth
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./database/init.js:/docker-entrypoint-initdb.d/init.js